### ISSUE TITLE
from .core import save_to_cache error

### ISSUE THREAD

**Issue by Mehdi2566** [gboeing/osmnx#106]
can anyone help me with this error?
the error is Modulenotfounderror: no module named '__mai__.core' ; "__main__' is not a package

```python
# from .core import save_to_cache error
```

**Comment by gboeing** [comment]
@Mehdi2566 thanks for using OSMnx. Can you add the necessary information specified in the issue template guidelines so that we have enough info to help you troubleshoot? We need a full working code example to run to reproduce the error. We also need some info about your environment, packages, what you were trying to do, what you expected to happen, and what actually happened. If an error occurred, please provide the full traceback message.

**Comment by gboeing** [comment]
see #108
