### ISSUE TITLE
Simplifying Topography- Paths that need to be removed question

### ISSUE THREAD

**Issue by martham93** [gboeing/osmnx#119]
Hi, your package OSMnx is awesome! I have a question about simplifying network topology. I’ve read the documentation and looked at the example notebook, but I’m still a little confused.

For example, using the Piedmont, CA roads, once that graph is saved as a shapefile some rows have multiple geometries and osmids. When I check to see if the graph G is simplified I get true, but when I run the function ox.simplify.get_paths_to_simplify(G, strict=True) I get a list of 32 paths that need to be simplified. 

How can I make sure these paths that need to be simplified are removed in both the graph and shapefile format? 
Thank you. 

[gist with example code](https://nbviewer.jupyter.org/gist/martham93/227241f7942020e937fcd5f90ab195d6)

**Comment by gboeing** [comment]
Hi @martham93 thanks for using OSMnx. There are three issues here -- let me disentangle and explain. You said:

> once that graph is saved as a shapefile some rows have multiple geometries and osmids

First, edges should *not* have multiple geometries, and indeed in your example it looks like they don't. The example you gave of multiple geometries looks like this:

```
LINESTRING (566271.4447110506 4186299.534619553, 566261.8282031068 4186306.713795525, 566137.8142594484 4186414.798487118, 566186.4644187745 4186474.463878916)
```

That is a single geometry. It's a single [shapely LineString](https://toblerity.org/shapely/manual.html#LineString) object with multiple vertices defining the line. It has multiple vertices because this street (i.e., graph edge) has curves in its spatial geometry. So this all checks out fine.

Second, a simplified edge *can* have multiple OSM IDs, or other attributes for that matter. Simplification merges edges together to remove pseudonodes that simply form an expansion graph -- that way, the end result is a graph that has nodes only at intersections and dead ends. When this merge occurs, OSMnx makes a list of the merged edges' attribute values if they were not the same. For example, if you see a list of highway types like ['primary', 'primary_link'], it means that edges with these two types were merged together into a single edge in the simplified graph. Or in your example, if you see a list of osmid values like [6327300, 6339118], it means that edges with these two OSM IDs were merged together into a single edge in the simplified graph.

Third and finally, regarding `get_paths_to_simplify` showing more paths that need to be simplified *after* you have simplified the graph... in your example, the first set of nodes that it says to simplify are:

```
[53036558, 53028192, 53028190]
```

Here's what those three nodes look like (in yellow) in a segment of your simplified graph:

![simp](https://user-images.githubusercontent.com/4977197/34852462-9e16d282-f6e3-11e7-8ec0-f104a76e4375.png)

Superficially it does look like there's a path to be simplified there to remove that interstitial "middle" node! But now look at that middle node [on OpenStreetMap](https://www.openstreetmap.org/node/53028192). It is indeed a true intersection, so OSMnx retains it in the graph. However, all the other streets it connects to have their other endpoint nodes *outside* Piedmont's borders, so those other endpoints are not contained in this graph (which you defined as constrained to Piedmont's borders), and thus the edges cannot be contained in this graph. Artificial boundaries are always imposed on street networks (unless you look at the entire continent-wide street network as a whole) and they result in artifacts like this around their periphery. You can look up in the graph's data dictionary how many streets are connected to this node in the real world:

```python
G.graph['streets_per_node'][53028192]
# returns 4
```

So OSMnx knows that four streets are indeed connected to this peripheral node in the real world (essential information for studying this street network for transportation or urban design), but it also knows that it doesn't need to simplify the graph again, even though there are paths that *could* be simplified according to its algorithm, because of the artificial boundary (Piedmont's city limits) imposed on the street network.

Hope that explains in more detail what's going on and how OSMnx simplification works.

**Comment by gboeing** [comment]
@martham93 all good?

**Comment by martham93** [comment]
Yes! Thank you so much. Your explanation was very helpful.
