### ISSUE TITLE
We need a fucntion that can generate  gdf_nodes and gdf_edges from locallly  downloaded road network loaded using geopandas as gdf

### ISSUE THREAD

**Issue by SammyGIS** [gboeing/osmnx#1194]
### Contributing guidelines

- [X] I understand the contributing guidelines

### Documentation

- [X] My proposal is not addressed by the documentation or examples

### Existing issues

- [X] Nothing similar appears in an existing issue

### What problem does your feature proposal solve?

I have a road netwrok data downloaded on my laptop, I loaded it as geodataframe and I want to convert it to graph, but I need to generate gdf edges and gdf_nodes and nothing is working for me. I don't want to load it directly from osm

### What is your proposed solution?

We should have two functions separately that you can use to generate gdf nodes and gdf_edges, and we should be able to generate graph from gdf loaded via geopandas and  already downloaded road network line

### What alternatives have you considered?

I used momepy to generate graph, but the graph it generated does not meet the requirement of osmnx edges and nodes.
The nodes and graph lacks  (x,y) for nodes and (u, v, key) in edges. Therefore money pay graph from gdf is not working fine 

### Additional context

```
import geopandas as gpd
import osmnx as ox

road_file = 'gis_osm_roads_free_1.shp'

# Read in the road network data as a GeoDataFrame
road_gdf = gpd.read_file(road_file)


gdf_nodes, gdf_edges, = ox.graph_to_gdfs(project_graph ,nodes=True, edges=True)

# Reconstruct graph from GeoDataFrames
road_network_graph = ox.convert.graph_from_gdfs(gdf_nodes, gdf_edges, graph_attrs=None)

utm_crs=27700
#project graph from WGS84 to UTM
project_graph = ox.project_graph(road_network,to_crs=utm_crs)
```

 what I have is a gdf not a graph and to convert gdf to graph I need the gdf nodes and the gdf edges, so how do I  generate this, having a function that allows me to generate this before I then converted my data from gdf to graph will be really fantastic.

**Comment by gboeing** [comment]
Provide a link to the shapefile you're trying to load. It all depends on the details of the data.

**Comment by SammyGIS** [comment]
> Provide a link to the shapefile you're trying to load. It all depends on the details of the data.

HEre is the lin to the 
https://download.geofabrik.de/europe/united-kingdom/england/west-yorkshire-latest-free.shp.zip

**Comment by gboeing** [comment]
You cannot create a graph from this roads shapefile in any straightforward way. It consists only of edge geometries. There is no topological information and no nodes data.

> We should have two functions separately that you can use to generate gdf nodes and gdf_edges, and we should be able to generate graph from gdf loaded via geopandas and already downloaded road network line

There is no way to do this in a generalizable way, because the only functionality you need is entirely dependent on the source data. In your specific case, it'll be particularly difficult. But if you *must* use this shapefile for some reaason, then you'll want to develop a series of functions to do the following:

1. Find the intersection points of all the OSM ways with each each other to identify "candidate" nodes.
2. Filter those candidate node points to remove non-intersections (i.e., based on the bridge/tunnel attribute data)
3. Identify dead-end nodes by finding the terminal vertex of each way, where that vertex does not co-locate with an intersection point.
4. Break the ways on the node points to create edges and determine source/target nodes for each.
5. Construct the graph from the nodes and edges GeoDataFrame.

This will all be non-trivial but potentially possible for you.

>  I don't want to load it directly from osm

Remember that OSMnx caches Overpass API responses. So, just like how you downloaded this shapefile once here, you can use OSMnx to download the graph data just once from Overpass then easily build your graph model. I'd recommend this path as its a one-time download and very easy (1 or 2 lines of code).
