### ISSUE TITLE
Diameter from networkx.diameter() and osmnx.extended_stats() differ

### ISSUE THREAD

**Issue by gredoldolin** [gboeing/osmnx#129]
Hey Geoff,

Thank you for this fantastic library. I'm pretty new to Python, but I think your library is the one I use most often.

I was a little bit confused when I looked at the diameter of the Back Bay street network in Boston. If I use `nx.diameter()`, I first need to convert the directed graph into an undirected one. However, then I cannot use it with `ox.extended_stats()` because it throws the `NetworkXNotImplemented: not implemented for undirected type` error.

On the other hand, passing a directed graph into `nx.diameter()` also throws the error `NetworkXError: Found infinite path length because the digraph is not strongly connected`.

```python
G = ox.graph_from_place('Back Bay, Public Alley 433, Chinatown, Back Bay, Boston,Suffolk, Massachusetts, 02118, United States of America', network_type='drive_service')
G_simple = nx.Graph(G)
print(nx.diameter(G_simple))
print(ox.extended_stats(G, ecc=True)['diameter'])
```
So eventually, the outcome is:
`nx.diameter(G_simple) = 26` This seems to be the total number of all edges.
`nx.extended_stats(G, ecc=True)['diameter'] = 3251.23079746` This seems to be the total length of all edges.

Is it because NetworkX uses `nx.single_source_shortest_path_length()` and OSMnx uses `nx.single_source_dijkstra_path_length()`?

Thank you.

**Comment by gboeing** [comment]
@gredoldolin thanks for using OSMnx. If you [look inside](https://github.com/gboeing/osmnx/blob/54ee4be1e65c33a41c5751a3ea80a195987a6582/osmnx/stats.py#L301) the `stats` module, you'll see that OSMnx automatically converts the street network MultiDiGraph to a DiGraph called `G_dir`, a MultiGraph called `G_undir`, and the largest strongly connected MultiDiGraph component called `G_strong` to calculate measures that require any of these graph types.

Yes, to precompute the shortest paths used for all the eccentricity-based measures, OSMnx uses `nx.single_source_dijkstra_path_length`, but more importantly, it weights the edges by their `length` attribute (in meters) because this is a spatial network. So in other words, in your example, 26 is the graph distance and 3251.23 is the metric distance of the path.
