### ISSUE TITLE
Select edges and nodes by attribute

### ISSUE THREAD

**Issue by JoaoCarabetta** [gboeing/osmnx#144]
First of all, great repo! 

I was using the function `get_edge_colors_by_attr` and I got curious to know what are the other attributes available. I noticed that each edge carries some attributes like `highway`, `lanes`, `maxspeed`, etc. These are attr that carry quite interesting information which could be useful to map. 
However, the function does not map them mainly because they are categorical.

![image](https://user-images.githubusercontent.com/19963732/37791755-cb6fdcf6-2de8-11e8-9154-048b1191889a.png)

With that in mind, I looked for a function to select specific categories from a map, such as `highway = primary` or `lanes = 2`, but I couldn't find it. The only functions that do something like that are the downloading ones, but they do not work with already loaded data. 

Given that, I suggest two improvements that I can implement myself. 

#### 1. Edges/Nodes selection by attributes. 
```python
def select_[edge|node]_by_attr(G, attr):
    """
    Get the [edge|node] that matches a attribute. 
Parameters
    ----------
    G : networkx multidigraph
    attr : string
        the name of the continuous-variable attribute
        [List of available attributes]

    Returns
    -------
    nx.graph with selected [edges|nodes\
   """
```

#### 2. Edges/Nodes colouring by attributes.
```python
def get_[edge|node]_colours_by_attr(G, attr, num_bins=5, cmap='viridis', start=0, stop=1):
    """
    Get a list of [edge|node] colours and its categories. 
    If the variable is continuous it bins the attribute into quantiles.
    If the variable is categorical it just assign colours.
Parameters
    ----------
    G : networkx multidigraph
    attr : string
        the name of the continuous-variable attribute. 
        [List of available attributes]
    num_bins : int
        how many quantiles. Only works for numerical attributes
    cmap : string
        name of a colormap
    start : float
        where to start in the colorspace
    stop : float
        where to end in the colorspace

    Returns
    -------
    colours: list, categories: dict
   """
```

Do you think that it makes sense to work on those improvements. Did I miss something and these features already exists? 

Cheers!

**Comment by gboeing** [comment]
Thanks @JoaoCarabetta for the suggestion! The main reason the former function doesn't exist in OSMnx is because it can be easily done with a single line of code like:

```python
[(n, d) for n, d in G.nodes(data=True) if 'highway' in d and d['highway']=='turning_circle']
```
or
```python
[(u,v,k,d) for u,v,k,d in G.edges(keys=True, data=True) if d['highway']=='secondary']
```
As it's easy for a user to implement ad hoc, I'm not sure it's a substantial value-add to include in the package. I've tried to leave out things like that to make there be fewer loose ends of code to maintain. But I'm open to having my mind changed if there's a good alternative argument.

Regarding the latter function, I think this is a good idea, and in fact `get_edge_colors_by_attr` should be generalized and enhanced to work with nodes or edges, and continuous or categorical variables. It would also benefit from handling cases where binning doesn't create unique bin edges (I don't believe it handles this well right now). Would you be interested in putting together such a function as a PR? Easier to discuss and make any tweaks that way.

**Comment by gboeing** [comment]
Closed for inactivity. Can reopen at later date.
