### ISSUE TITLE
Inaccurate streets_per_node count

### ISSUE THREAD

**Issue by j-t-t** [gboeing/osmnx#200]
#### Problem description (what did you do, what did you expect to happen, and what actually happened)
Sometimes openstreetmap has two ways, one of which is contains a subset of the nodes that the other one has. This appears to happen when a street is partially one way and partially two ways.

Two examples of this are:
- https://www.openstreetmap.org/way/12169562 and https://www.openstreetmap.org/way/581179498
- https://www.openstreetmap.org/way/12117965 and https://www.openstreetmap.org/way/581179505

get_streets_per_node is saying that nodes in these ways have more streets than they actually do (https://www.openstreetmap.org/node/110343271 and https://www.openstreetmap.org/node/109852721 are the nodes on those ways that I'm looking at)

#### What operating system, architecture, Python version, and OSMnx version are you using?
Ubuntu 18.04.1, Python 3.6.6, osmnx 0.8.1 

#### Code that reproduces the issue

```python
import osmnx as ox

G = ox.graph_from_point((40.0821012, -75.0827512),
                        1000,
                        network_type='drive', simplify=True)

streets_per_node = ox.count_streets_per_node(G)
print(streets_per_node[110343271])
print(streets_per_node[109852721])
```
The streets per node printed are 5 and 2, and looking at the nodes in openstreetmap (https://www.openstreetmap.org/node/110343271 and https://www.openstreetmap.org/node/109852721 respectively) it seems like it should be 4 and 1.

**Comment by gboeing** [comment]
As far as I can tell, this is a problem with the source data on OSM rather than with OSMnx. For example, if a road is one-way, then it should tagged [as such](https://wiki.openstreetmap.org/wiki/Key:oneway). It appears that parts of [Borbeck Ave](https://www.openstreetmap.org/way/12169562) are one-way, but they are not tagged as such. Instead, the digitizer just layered two road lines atop one another where it is two way, and laid a single road line where it is one-way. OSMnx is correctly identifying these ways and marking them as separate roads at the intersection. It seems that this should be corrected on OSM, and then OSMnx will count those roads properly.

**Comment by j-t-t** [comment]
What you're saying makes sense: it does appear to be an OSM data issue. It would be nice if it were possible to identify the correct number of streets per node despite this, since we're using that function on cities we've possibly never seen before, and we wouldn't know in advance if the OSM data is bad. We've only seen it in the Philadelphia area so far though, and have a (sort of hacky) workaround, so we can live with it rather than fixing the OSM data.

Thanks for your work!
