### ISSUE TITLE
Include turn restrictions?

### ISSUE THREAD

**Issue by maning** [gboeing/osmnx#22]
Great tool!  For modelling routes, does this module incorporate turn_restrictions? In OSM, it is modeled as relations.

**Comment by gboeing** [comment]
At the moment it does not, but I'm looking into adding this into an upcoming release.

**Comment by gboeing** [comment]
While I like the idea of this in theory, it looks like it's beyond the scope of OSMnx. A robust routing package built on top of OSMnx could perhaps be a better future home for this functionality. Directional turn restrictions provide a nontrivial algorithmic challenge. OSMnx uses NetworkX's path calculation algorithms, and they don't account for spatial networks with turn restrictions. Using something like [SimpleOsmRouter](https://github.com/F6F/SimpleOsmRouter) or [PyRoute](http://svn.openstreetmap.org/applications/routing/pyroute/) might work for your application. But at this point, adding this functionality is beyond the project scope.

**Comment by higee** [comment]
@gboeing Any news for this issue? 

I wonder if you by any chance have started working on this issue. I found out that [pgRouting](http://pgrouting.org/), for instance, offers TRSP (turn restriction shortest path). I really am a big fan of osmnx and want to stay in this platform. 

If not, could you provide me with any kind of hint so that I could try customizing osmnx and probably networkx by myself? I'm fully aware of the fact that it might become a huge project as you've mentioned couple month ago. 

I'm also curious whether @maning found a way to this issue.

**Comment by gboeing** [comment]
@higee I haven't worked on it further for the reasons I mentioned previously. But I'm open to it if it's feasible to incorporate TRSP with a python package. Keep me posted if your explorations uncover something useful.

**Comment by higee** [comment]
@gboeing Could you share your email address? I wrote down some issues and my approaches with images inside pdf file. I tried uploading here but somehow it doesn't go up.
