### ISSUE TITLE
Python: error using osmnx during building extraction

### ISSUE THREAD

**Issue by emanuelemassaro** [gboeing/osmnx#268]
I would like to extract the building layer information from in Haiti using osmnx. It works for different cities it does not in the case of "Port-au-Prince" for instance

```python
import osmnx as ox
place_name = "Port-au-Prince"
buildings = ox.buildings_from_place(place_name)
I get the following error

TypeError: Geometry must be a shapely Polygon or MultiPolygon
```

**Comment by gboeing** [comment]
The API is not successfully geocoding your place name. Try to make it more explicit, or pass a dict instead of a string. More details are in [this docstring](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.core.graph_from_place) and various closed issues such as #11 #16 #31 #102 #118 #176 #207
