### ISSUE TITLE
Document change to OpenStreetMap node format

### ISSUE THREAD

**Issue by dHannasch** [gboeing/osmnx#276]
Unless I missed it, the documentation does not currently explain the meaning of the 'x' and 'y' attributes on nodes. (OpenStreetMap calls these 'lon' and 'lat'.) If you want, we could add a note of that, e.g. like https://github.com/dHannasch/osmnx/commit/4e3a9b393f7731ed65240437b20b98004a746a8d#diff-8aa79b83ed86e48962cc94787fc5cb56 .

**Comment by gboeing** [comment]
`x` and `y` are standard geospatial attributes partly because they *don't* always mean lat and lon... for example, someone may load a .osm file with node coordinates in a different reference system, or someone may have projected a graph to a planar coordinate reference system (in both of these examples, the coordinates OSMnx is working with are x and y, not lat and lon). For that reason, it's probably best to not hard-code reference to lat/lon as these attributes often do not refer directly to lat/lon.
