### ISSUE TITLE
Feature Request: asynchronous requests

### ISSUE THREAD

**Issue by duccioa** [gboeing/osmnx#344]
Hello,
I am trying to download graphs from cells like administrative boundaries or statistical units. This consists on looping through the geometries of a  `geopandas` dataframe  and send a request with `graph_from_polygon`.    
Beside the problem of overloading the Overpass API (as I understand #328 should allow the use of a different endpoint), my problem is that these geometries can count up to the ten-thousands or even more and the process can take weeks.    
Would it be feasible to add a function say `graph_from_geopandas` that makes use of threading, multiprocessing or asynchronous requests to speed up the downloading (it seems to me that `asyncio` could do the job)? Would you be interested in adding it to the package?
If I wanted to try to implement such a function, how would you go about it?

Anyway, thank you for the great work! I really appreciate what you are doing.
Duccio

**Comment by kylebarron** [comment]
Doing tens of thousands of overpass queries in parallel is probably against their terms of use, or at a minimum I'm sure they'd want some type of rate limiting.

In any case, for your use case it sounds like it would be better to download an extract of a large region of interest from http://download.geofabrik.de/ and then use `graph_from_file`. Note you'd need to download and extract the `.osm.bz2` file format.

**Comment by duccioa** [comment]
Thank you Kyle. As I mentioned, I understand bombarding the Overpass API would probably go against their terms of use and it should be done on a local copy. 
The solution you are proposing is something that I tried and it is not very practical when you need to fetch the network from bespoke polygons. You need to first cut the `.osm.bz2` file using `osmosis` then either write the subset to disk or send the standard output to Python and then using `graph_from_file`. 
Loading the file from the standard out still requires the tweaking  of `osmnx` and I would still need to make the process run in parallel to make it fast enough. I thought this would be time better spent to make a proper osmnx function to loop through multiple geometries and send asynchronous requests to a local copy of the API. 

This might or might be not an interesting feature for `osmnx`, but I would still be grateful if some more experienced programmer than me could point at the right direction on how to implement it.

Thanks

**Comment by kylebarron** [comment]
Have you tried running `osmfilter` in parallel to get extracts for each polygon? I've found that `osmfilter` is quite fast, and I would expect that as a shell script there would be no issues running it in parallel.

Otherwise, if you still want to use Overpass API locally, I did google "python concurrent http requests" and there are many, many blog posts for how to implement such a thing, though it's not trivial, or at least requires understanding Python's concurrency model in more depth. So maybe modify osmnx to return the HTTP request string for each polygon, then send the request concurrently.

But also, if you're setting up Overpass API locally, non-concurrent requests might be enough since you'd have very little latency.

**Comment by kylebarron** [comment]
Also if you use `capture_output=True` on [`subprocess.run`](https://docs.python.org/3/library/subprocess.html), I think that returns the output from `osmfilter` (haven't used osmosis) as a Python string. ~~Then you should be able to just pass that string to `graph_from_file`, no?~~ I see that `graph_from_file` only accepts a filename. That should be updated to accept a filename or buffer, so that you could put a string into a `StringIO` buffer to pass to the command.

**Comment by gboeing** [comment]
@duccioa yes, as @kylebarron suggests, an important goal of the OSMnx project is to not overload the APIs we use. I built responsive rate-limiting into OSMnx and this doesn't accommodate parallel processing. A couple thoughts: 1) geofabrik may be a good option for acquiring large study areas. 2) a local overpass api instance may meet your needs. 3) when I've modeled tens of thousands of study sites before (say, census tracts) I let it run overnight and with the responsive rate-limiting it finished in a day or so.
