### ISSUE TITLE
ox.graph_from_place / Need some advice

### ISSUE THREAD

**Issue by RCC-GIT** [gboeing/osmnx#348]
Hello, I am testing OSMNX which very efficient ...I want to get roads in Shape files for France.
So this is my first code :
 ```
> dept="Finistére, Bretagne, France"
> G = ox.graph_from_place(dept, network_type='drive',infrastructure='way["highway"~"primary"]')
> G_projected = ox.project_graph(G)
> save_R='dep-finistere-primary-shape'
> ox.save_graph_shapefile(G_projected, filename=save_R)
```

I Works OK  but I have 2 issues : 

When I wants to get all the drive of this big area , it goes endless ... I think because the quantity of data is too big .... So What are the limitations ? Can I get only the .shp files because the .dbf files can we very  big rapidly ? How can I reduce the size of data to download ?

I do the retreive with => infrastructure='way["highway"~"primary"]' , But I am olnly interested at this level with  the drives on which information is in column REF (D15 or N12 ....)  . Is it possbile to retreive on REF in order to reduce the quantity of data .?

highway,C,80 | junction,C,80 | oneway,C,80 | length,C,80 | from,C,80 | to,C,80 | ref,C,80
-- | -- | -- | -- | -- | -- | --
primary | roundabout | True | 58.28900000000001 | 371859457 | 371859508 |  
primary |   | True | 47.620999999999995 | 1105578227 | 371859457 | D 15
primary | roundabout | True | 20.845 | 264212327 | 371859457 |  
primary | roundabout | True | 46.182 | 355328006 | 258054122 |  
primary | roundabout | True | 31.186 | 371867466 | 355328006 |  
primary |   | True | 398.45500000000004 | 264212327 | 355328006 | D 15
primary |   | True | 26.51 | 1134555144 | 1134555204 | D 783
primary |   | False | 769.7739999999999 | 1134637928 | 1134555144 | D 783
primary |   | True | 30.277 | 1134555098 | 1134555144 | D 783

Thanls for your advice.

**Comment by gboeing** [comment]
@RCC-GIT if you decompose and time your code, you'll see that you can get the entire drivable network for this area in just like ~4 minutes. The time complexity arises when you try to project your (huge) simplified graph. As has been discussed elsewhere in this issue tracker, the fastest workflow is to:

  1. get the graph without simplifying it
  2. project the graph to your desired CRS
  3. simplify the projected graph

This is because geopandas (under the hood) projects your simplified geometries edge-by-edge, which takes a very long time when you have a million of them. It's much faster to project unsimplified edge geometries. So, do something like:

```python
import osmnx as ox
ox.config(log_console=True, use_cache=True)
G = ox.graph_from_place('Finistére, Bretagne, France', network_type='drive', simplify=False)
G_projected = ox.project_graph(G)
G_simple = ox.simplify_graph(G_projected)
ox.save_graph_shapefile(G_simple, filename='dep-finistere-primary-shape')
```

Now you can filter your graph by whatever values in the REF attribute you like.

**Comment by gboeing** [comment]
In case anyone else comes along here looking for information, please note that the old infrastructure parameter was deprecated and replaced by the custom_filter parameter in a recent release.
