### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by yuriniet** [gboeing/osmnx#385]
Since yesterday (12, February), the command graph_from_address is not working anymore.

The errors and details are in the image below. 

![c](https://user-images.githubusercontent.com/44909812/74436020-7a034a00-4e44-11ea-8344-1c390ba334a6.png)

**Comment by gboeing** [comment]
Please fill out the new issue template completely and I can take a look.

**Comment by KyleHarrison** [comment]
Have been dealing with this for the past 24 hours as well. Only graph_from_address results in this.

Running:
```
import requests
url = 'https://nominatim.openstreetmap.org/search?format=json&limit=2&dedupe=0&polygon_geojson=1&q=City of London, UK'
req = requests.get(url)
```
`<head>\n<title>Access blocked</title>\n</head>\n<body>\n<h1>Access blocked</h1>\n\n<p>You have been blocked because you have violated the\n<a href="https://operations.osmfoundation.org/policies/nominatim/">usage policy</a>\nof OSM\'s Nominatim geocoding service. Please be aware that OSM\'s resources are\nlimited and shared between many users. The usage policy is there to ensure that\nthe service remains usable for everybody.</p>\n\n<p>Please review the terms and make sure that your\nsoftware adheres to the terms. You should in particular verify that you have set a\n<b>custom HTTP referrer or HTTP user agent</b> that identifies your application, and\nthat you are not overusing the service with massive bulk requests.</p>\n\n<p>If you feel that this block is unjustified or remains after you have adopted\nyour usage, you may contact the Nominatim system administrator at\nnominatim@openstreetmap.org to have this block lifted.</p>\n</body>\n</head>`

I have tried changing the config _default_user_agent_, _default_referer_ and _overpass_endpoint_. To no avail. 

I emailed the Nominatim system administrator and received this response:

> Hi,
> you have been blocked because you have violated the usage policy
> (see https://operations.osmfoundation.org/policies/nominatim/).
> Please review the terms and make sure that your
> software adheres to the terms. You should in particular verify
> that you have set a **custom HTTP referrer or HTTP user agent** 
> that identifies your application. In your case you might want
> to ask the maintainers of OSMnx to review the usage policy.
> 

I had used the example notebooks only a few times before this. I had only used the package for a day, I doubt I have made excessive requests.

**Comment by gboeing** [comment]
Thanks @KyleHarrison I think that gives me enough to go on to fix this...

**Comment by gboeing** [comment]
fix in #386

**Comment by gboeing** [comment]
The problem was that the `geocode` function was directly calling the nominatim API rather than using the `nominatim_request` function which handles all the caching, user-agent, referer, etc. Fixed now in the master branch if you want to test it.

**Comment by yuriniet** [comment]
Thank you so much! Now it works! And thanks for the excellent module.
