### ISSUE TITLE
Proposal: Enable simplification of long (rural) roads

### ISSUE THREAD

**Issue by pinselimo** [gboeing/osmnx#488]
Hi!

Downloading a rural, mountainous and rather big area, I've run into the issue that some roads are not simplified properly. This is well documented and happens due to a ```RecursionError``` in ```simplification._build_path```. This error is subsequently caught in line 171 (commit 0ef7002) and logged.

I've had this issue monkey patched so far. Now I forked osmnx and implemented it correctly. It is tested and ready for a PR, However, I opened the issue in order to conform to the contributing guidelines.

#### Further changes for large networks and compatibility:

In a separate commit I've turned ```simplification._get_paths_to_simplify``` into a generator to keep its memory footprint in large networks lower. Also at some point I found that it raises errors with ```Python<3.5``` so I've exchanged ```RecursionError``` for ```RuntimeError```, where the prior is a subtype of the latter, so behaviour remains the same.

#### Testing

All of the above mentioned commits on my branch have been tested according to the contributing guidelines.

cheers,
Simon

**Comment by gboeing** [comment]
Thanks @pinselimo. Yep this is a known issue due to recursion depth. If you've found a solution for it, I'd be glad to examine a pull request. A smaller memory footprint would also be welcome.

One note: the previous two releases of OSMnx are compatible with the three most recent major releases of Python (3.6, 3.7, 3.8) and Python 2 support was dropped last year. It's best to use `RecursionError` as that's the specific error being generated and is compliant with all versions of Python supported by this package.
