### ISSUE TITLE
Add alternative elevation provider

### ISSUE THREAD

**Issue by janiksudo** [gboeing/osmnx#512]
Because Google Maps is not free, and the monthly 200$ budget does not even cover fetching node elevations for one big city, I looked for alternative REST-style APIs that provide elevation data.

Airmap (https://developers.airmap.com/docs/elevation-api) weirdly seems to be free, permanent and without quotas.
I was able to add node elevation for three different network types (walk, bike, drive) for multiple cities without running into limitations. The biggest network was >80.000 nodes and fetching elevation data in batches of 1000 took less than two minutes.

I am happy to prepare a pull request with the minor changes necessary to the elevation module such that one can use something like a `provider=Airmap` function parameter (defaulting to Google Maps?) when calling `add_node_elevations`.

Note though, that the elevation resolution is not as good as with GMaps (elevation is in integer meters). The spatial resolution seems to be similar to SRTM30m datasets. A limitation is that the elevation dataset "is limited to latitudes from 56ºS to 60ºN" (another hint at SRTM30m).
These limitations, however seem like a fair trade-off for everyone that willingly uses the alternative provider.

**Comment by gboeing** [comment]
Thanks @janiksudo. I'm potentially open to reviewing a PR for this if the code changes are relatively simple. Rather than a new `provider` parameter, I'd suggest adding `elevation_api_endpoint` to the `settings` module and `utils.config` function, similar to how custom nominatim API endpoints are handled.

One note:

> the monthly 200$ budget does not even cover fetching node elevations for one big city

You can attach elevations to 16 million nodes per month given the free allowance. A big city like New York's urban area has on the order of 250,000 nodes, if you are working with a simplified graph.

So, given a $200 monthly free allowance (equating to 40,000 API calls), the 8192 URL character limit, and `max_locations_per_batch=400`, I have attached the node elevations to every node in the entire US. With $600 (i.e., spread the free allowance across either 3 months or 3 API keys) I have attached all the node elevations for every urban area worldwide in the global human settlements layer.

**Comment by janiksudo** [comment]
> given a $200 monthly free allowance (equating to 40,000 API calls), the 8192 URL character limit, and `max_locations_per_batch=400`

Something new every day... Thanks for making me look again at the cost structure of the Maps API - I was assuming 0.005$ per single Elevation Point. (facepalm)

I will still prepare a small pull request because I think the option of a completely free provider next to GMaps is useful.
