### ISSUE TITLE
clean_intersections geoseries only returning one observation

### ISSUE THREAD

**Issue by kaseyklimes** [gboeing/osmnx#53]
Trying to get the clean intersections from within a polygon as efficiently as possible. I've hacked it down to the following. I understand the output of `ox.clean_intersections` should be a geoseries, but `i` only returns one observation here. Not sure if I'm missing something or if it's a problem in osmnx.

I'm on Mac OS 10.12.3, using python 2.7.13, OSMnx 0.51 (direct from github)
```
import osmnx as ox, geopandas as gpd
%matplotlib inline
ox.config(log_file=True, log_console=True, use_cache=True)

cbsa = gpd.read_file('cbsa.shp')
metro = cbsa[(cbsa['name']=='test')]
polygon = metro['geometry'].iloc[0]
G = ox.graph_from_polygon(polygon, network_type='walk')
i = ox.clean_intersections(G, tolerance=15, dead_ends=False)
print i
```

in this case it only returns
```
0    POINT (-122.2386546530941 37.80847450092825)
dtype: object
```

---
update: realize I need to project the graph with `ox.project_graph(G)` but this slows the script down a lot. Is there a way to only project the nodes and not the edges?

**Comment by gboeing** [comment]
You have a couple options. 1, you could work in degrees instead of meters (ie, pass `tolerance` in units of degrees). But this isn't a very good option as degrees can behave inconsistently at different latitudes. 2, you could project the whole graph to meters and then work in meters. But projection is fairly slow, as you mentioned. 3, you could speed up projection by passing `simplify=False` into `graph_from_polygon`. The biggest slowdown for graph projection comes from the edge LineStrings. Then simplify the graph after it has been projected, and then clean the intersections.

See cell 10 and the note below it: https://github.com/gboeing/osmnx/blob/master/examples/03-example-osm-place-network.ipynb

**Comment by kaseyklimes** [comment]
Thanks Geoff! I actually took your code and hacked together a `project_graph_nodes` function that projected only nodes and ignored edges. It worked but your 3rd option is a bit faster.

One more question though... when I try to project to a specific crs with `project_graph` it goes back to only returning a single observation like before. Is my syntax wrong here?

```
cities = ["city01", "city02", "city03"]
for city in cities:
    cbsa = gpd.read_file('/cities.shp')
    metro = cbsa[(cbsa['name']==city)]
    polygon = metro['geometry'].iloc[0]
    G = ox.graph_from_polygon(polygon, network_type='walk', retain_all=True, simplify=False)

    G_proj = ox.project_graph(G, to_crs={'init': 'epsg:4326'})
    G2 = ox.simplify_graph(G_proj)
    i = ox.clean_intersections(G2, tolerance=15, dead_ends=False)
    i.to_csv('/%s.csv' % city, sep=',', decimal='.')
```
(Sorry for posting this in issues as now it's clearly not a bug – is there a preferred forum for these questions?)

**Comment by gboeing** [comment]
EPSG 4326 uses degrees as its units, so your tolerance value is *15 degrees*. Project it to a CRS that uses meters as its units and your code will work. For example, you could use something like EPSG 26910, which is UTM zone 10n.

**Comment by kaseyklimes** [comment]
Of course, thanks Geoff! Having fun with this.
