### ISSUE TITLE
osmnx.utils_geo.bbox_from_point(point, dist=1000, project_utm=False, return_crs=False) too slow for "big" datasets

### ISSUE THREAD

**Issue by diego-florez** [gboeing/osmnx#540]
Hi! 1st of all I have to say this package is amazing and super complete, really useful :)

**"Issue"?**

So I am using it to find Pois in 1km radius from a 55k rows dataset I am working with.
The point is that I wanted to obtain the bounding box from lat/long of all my points (55k). And it took 1h27min with the 
`bbox_from_point(dist=1000, project_utm=False, return_crs=False)` function.

This was my implementation:
`trash_df["bbox"] = trash_df.swifter.apply(lambda column: ox.utils_geo.bbox_from_point((column.latitude, column.longitude), dist=1000), axis=1)`

**Describe the solution you'd like to propose**

So I made this fn:

```
def getBbox(lat, lon, radius=1):
    import math
    
    R = 6371

    w = lon - math.degrees(radius/R/math.cos(math.radians(lat)))
    e = lon + math.degrees(radius/R/math.cos(math.radians(lat)))
    s = lat - math.degrees(radius/R)
    n = lat + math.degrees(radius/R)
    
    return (n, s, e, w)
```

And it takes 2seconds and the resulst are equal until 3rd-4th decimal

**Comment by gboeing** [comment]
Thanks @diego-florez. The current implementation of `utils_geo.bbox_from_point` is only really designed for one-off use and, as you noted, isn't very efficient because it: 1) projects the passed-in point to the local UTM projection, 2) buffers it, 3) projects back to lat-lng, and 4) gets the bounds of the buffer. A streamlined solution like you propose might be useful.

A few questions/comments first:

  1. If `R=6371`, it looks like you're working in units of kilometers right? Why not meters?
  2. If `R` represents the radius of the earth, what does the variable `radius` mean? Is that the distance for the bounding box? If so, a more obvious variable name would be good.
  3. The 3rd decimal place in decimal degrees would be something like ~100 meters. If creating a bbox 1000 meters in each direction from the center point, this is a pretty significant discrepancy in the results.
  4. I'm not sure how you derived the formulae for the bounding box, but it doesn't look quite right to me, and I think may account for the previous point. I might instead implement something like this:

```python
def get_bbox(point, dist=500):
    
    earth_radius = 6371000 #meters
    lat, lng = point
    
    delta_lat = (dist / earth_radius) * (180 / math.pi)
    delta_lng = (dist / earth_radius) * (180 / math.pi) / math.cos(lat * math.pi / 180)
    
    north  = lat  + delta_lat
    south  = lat  - delta_lat
    east = lng + delta_lng
    west = lng - delta_lng
    return north, south, east, west
```

I suspect this will yield nearly identical results to the current implementation of `utils_geo.bbox_from_point`, but be much faster.

**Comment by gboeing** [comment]
I just did some quick tests and I believe our two solutions are actually mathematically equivalent. They seem to yield results within approximately a 1 meter of the current `utils_geo.bbox_from_point` implementation.

**Comment by gboeing** [comment]
See proposed enhancement in #541.
