### ISSUE TITLE
Load saved graph_shapefile 

### ISSUE THREAD

**Issue by terratenney** [gboeing/osmnx#61]
I might be missing it, but didn't see anything in closed issues,  trying to load street network from shapefile? I can see load_graphml, but figured there would be a convenience function for the shapefile I just saved from "save_graph_shapefile". Even pointing me to how this would be loaded would be appreciated. 

Awesome package by the way, very impressive research.

**Comment by gboeing** [comment]
Thanks @terratenney. OSMnx does not load street networks from shapefiles because shapefiles are nontopological data structures and we would not necessarily be able to infer intersections, directionality, etc (not to mention the fact that we construct nonplanar directed graphs). If you want to load a shapefile as a nonplanar multidigraph with self-loops, you'd have to identify all the points where lines intersect, then determine if each is a true intersection in two dimensions (ie, neither line represents a bridge or tunnel). You'd also need all the edges to include directionality data so you know from which origin node to which destination node it points if it is one way.

**Comment by cgthigpen** [comment]
I wonder if @terratenney slightly mis-typed his original question - I think I have a similar question. Is there a way to load shapefiles, from the Census for example, into OSMnx to use as the boundary geometry for a street network query? There is a "save_gdf_shapefile" function, but no equivalent "load_gdf_shapefile". Perhaps this is trivial, but I'm still new to python, so your input would be helpful.

**Comment by gboeing** [comment]
@cgthigpen yes. See cell 11 in [this notebook](https://github.com/gboeing/osmnx-examples/blob/master/notebooks/01-overview-osmnx.ipynb), which loads a shapefile of neighborhood boundaries, extracts one neighborhood's geometry, and queries for the street network within this boundary.

**Comment by cgthigpen** [comment]
@gboeing Ah, wonderful! Thank you for the prompt response and the wonderful functionality of this library (that's the term, right? I come from R where we call the equivalent a "package").
