### ISSUE TITLE
Query by OSM ID

### ISSUE THREAD

**Issue by idshklein** [gboeing/osmnx#620]
When extracting data from nominatim, sometimes a user knows the exact osmid of an entity. The current state of osmnx.downloader.nominatim_request allows for search, reverse, or lookup, but not for details. When I try to feed the response to osmnx.geocode._geocode_query_to_gdf, It does not work, due to the different structure of the response. 

I believe that adding the details request_type to nominatim_request, and adding the parsing of its output in _geocode_query_to_gdf make a good solution.

**Comment by gboeing** [comment]
Can you provide an example nominatim request url to do this?

**Comment by idshklein** [comment]
```python
import osmnx as ox
import requests
import collections
params = collections.OrderedDict()
params['osmtype'] = 'R'
params['osmid'] = '2192363'
params['format'] = 'json'
params['polygon_geojson'] = '1'
headers = ox.downloader._get_http_headers()
url = ox.settings.nominatim_endpoint.rstrip("/") + "/" + "details"
response = requests.get(url, params=params, timeout=ox.settings.timeout, headers=headers)
response_json = response.json()
```

**Comment by gboeing** [comment]
Other folks have previously asked about the possibility of querying by OSM ID, and in theory I like the idea of this. *But* I believe it violates the Nominatim terms of use, as [stated here](https://nominatim.org/release-docs/develop/api/Details/):

> Warning
> The details page exists for debugging only. You may not use it in scripts or to automatically query details about a result. See Nominatim Usage Policy.

So, I don't believe OSMnx can query the details endpoint without running afoul of their terms of use. I think the best we can do is point interested users to the code snippet you've provided here to let them roll their own solution with a few lines of code.

**Comment by idshklein** [comment]
Ok. What about doing the same using overpass api? Implementing it in the current flow is a bit messy, but as far as I know, it does not breach terms of use.  
This is a similar approach:
```
[out:json][timeout:25];
// gather results
(
  
  relation(2192363);
  
);
// print results
out body;
>;
out skel qt;
```

**Comment by gboeing** [comment]
I'm not sure. I suppose the wider question is what would be the specific purpose of this functionality? Is it to pull in the details themselves of the element with that OSM ID? Is it, rather, to just get a polygon geometry within which to query for other elements (using the `geometries` and `graph` modules)?

**Comment by gboeing** [comment]
My understanding is that this is essentially about geocoding by OSM ID rather than place name. The biggest problem with using Overpass rather than Nominatim for pseudo-geocoding tasks is that we don't get geometry back. Nominatim provides polygon geojson data in the response, but Overpass doesn't. So if you query something like in your example:

```
[out:json][timeout:25];(relation(2192363););(._;>;);out;
```

You get a list of [elements in response](https://overpass-api.de/api/interpreter?data=[out:json][timeout:25];(relation(2192363););(._;>;);out;), comprising (potentially) nodes, ways, and relations. You'd then have to reconstruct a (multi)polygon from that. This makes this a much larger and more complex project than simply adding a new `geocode_osmid` function to query Nominatim.

Currently, if someone knows the OSM ID of the boundary entity within which they wish to query, they can look up its name then query by that. For example, to use your query, one could pull up [that OSM ID](https://www.openstreetmap.org/relation/2192363) then query by the corresponding name (Københavns Kommune) like:

```python
import osmnx as ox
gdf = ox.geocode_to_gdf('Københavns Kommune')
geom = gdf['geometry'].iloc[0]
G = ox.graph_from_polygon(geom, network_type='drive')
```

The drawback is that it's not fully automatic. However, if a user wants to query by many OSM IDs, they could do it programmatically using the `details` endpoint as you demonstrated in your earlier code snippet, though this usage may run afoul of the API's terms of use.

**Comment by gboeing** [comment]
Ok, here's a proposed solution that I think satisfies the spirit of your initial proposal using Nominatim but without hitting the "details" endpoint.

```python
import osmnx as ox
from collections import OrderedDict

params = OrderedDict()
params["format"] = "json"
params["polygon_geojson"] = 1
params["osm_ids"] = "R2192363"
rj = ox.downloader.nominatim_request(params, request_type="lookup")
```

This uses OSMnx's existing ability to query the "lookup" Nominatim endpoint. Wrapping that code in a new `geocode_osmid` function should provide you what you're looking for. I might try to whip up a quick demo PR.

**Comment by gboeing** [comment]
@idshklein see #626 for proposed solution
