### ISSUE TITLE
No Attribute "Point"

### ISSUE THREAD

**Issue by mschroen** [gboeing/osmnx#656]
In an old version of osmnx, I successfully calculated the distance of a point to a line with:

`   data['distance'] = [ox.Point(tuple(point)).distance(line) for line in data['geometry']]`

However, in the recent version, `.Point()` does not exist anymore. I cannot find any documentation in the change logs how it should be replaced. Can you help out and maybe document the changes better?
Thanks!

**Comment by gboeing** [comment]
Hi @mschroen. I don't know what package version(s) are in discussion here and I can't reproduce your example, because the issue template's details weren't filled out and there isn't a minimal reproducible code snippet provided. Here's my best guess.

This should have never worked, even in the past, and I'm not completely sure why it did. It was never a documented use. But it probably worked due to a bug in the API allowing backdoor access to `shapely.geometry.Point` by inadvertently exposing it in the top-level namespace. This would have been fixed several releases ago, during last spring's API clean-up project.

> Can you help out and maybe document the changes better?

  - The API changes are all documented in #526.
  - All changes are documented in the [change log](https://github.com/gboeing/osmnx/blob/master/CHANGELOG.md).
  - The package's usage is documented in the [documentation](https://osmnx.readthedocs.io/).
  - The package's usage is demonstrated in the [usage examples](https://github.com/gboeing/osmnx-examples).

`ox.Point` would have never been documented or sanctioned in these official guides because if it did work, it was only inadvertently through a bug. If you want access to shapely `Point`, you should import it:

```python
from shapely.geometry import Point
data['distance'] = [Point(tuple(point)).distance(line) for line in data['geometry']]
```
