### ISSUE TITLE
Request: replace NetworkX with graph-tool under the hood for faster performance

### ISSUE THREAD

**Issue by geofurb** [gboeing/osmnx#710]
NetworkX seems to bottleneck performance on large graphs. Replacing it with [graph-tool](https://graph-tool.skewed.de/) would improve performance. I realize this is a massive undertaking and you're likely not interested, but I thought I might suggest it all the same.

(Fantastic tool! I'm loving it.)

**Comment by gboeing** [comment]
> NetworkX seems to bottleneck performance on large graphs.

It depends on what you mean: modeling or analysis? In terms of *modeling*, the bottlenecks are 1) downloading the data from OSM and 2) processing (and optionally simplifying) the graph to ensure you get the right attributes on each node to mitigate periphery effects. NetworkX doesn't pose a substantial performance drawback here. But in terms of *analysis*, NetworkX is indeed slow because it is pure Python, trading off speed for ease of use. I assume the bottleneck you're referring to here is in analysis? For example, it's nearly intractably slow to compute something like node betweenness centrality across a metropolitan-scale street network NetworkX graph.

Fortunately, there's already something of a range of solutions on the analysis side (and one of them is faster than graph-tool). They all trade off speed and ease of use. Here are four such options, sorted from easiest/slowest to hardest/fastest:

  1. Use the NetworkX graphs that OSMnx natively generates for your analysis (the default).
  2. Convert your NetworkX graph -> igraph for fast analysis in C/C++. See [example](https://github.com/gboeing/osmnx-examples/blob/v1.0.1/notebooks/14-osmnx-to-igraph.ipynb).
  3. Convert your NetworkX graph -> graph-tool for faster analysis in Boost/C++. See [conversion](https://bbengfort.github.io/2016/06/graph-tool-from-networkx/) [example](https://gist.github.com/bbengfort/a430d460966d64edc6cad71c502d7005).
  4. Convert your NetworkX graph -> cugraph for fastest analysis with CUDA and a GPU. See [documentation](https://docs.rapids.ai/api/cugraph/stable/).

You can play around with options 1-3 relatively easily by setting up a single conda environment with those packages:
```
conda create -n graph_test -c conda-forge --strict-channel-priority graph-tool igraph jupyterlab osmnx
```

Option 4 is more difficult to set up but potentially much faster than the others if you have a fancy modern Nvidia GPU. It has been my primary method for graph analysis in recent months.

OSMnx is built around NetworkX, so replacing NetworkX with a different library under the hood is outside our scope. In terms of performance, there's always a new kid on the block. Two years ago graph-tool was king. Today cugraph is faster. Who'll be fastest three years from now? And how hard will it be to install and/or use? NetworkX is ubiquitous, easy to use, and sufficiently fast for most use cases.

Short answer: converting NetworkX graphs to other graph libraries' types is relatively quick and simple and makes analysis much faster for those use cases where it's needed. The options listed above offer you maximum performance where it matters if you're working with a very large graph: in the analysis phase.

**Comment by geofurb** [comment]
Just building the network and checking connectivity is much faster in graph-tool, but I was pretty sure a rebuild wasn't in the cards. Since NetworkX is necessarily single-threaded, I was maxing out the CPU core for several minutes trying to get a street map of the NYC metro area.

**Comment by gboeing** [comment]
Yes. The cost of NetworkX under the hood is that it takes a few minutes to build a large metro area graph instead of <1 minute in graph-tool. But the much bigger performance cost is in analysis, where something that may take a few minutes in cugraph can take days to run in NetworkX. But you're right: for a large metro area, it takes a few minutes to build the graph as the cost of ease-of-use. For *subsequent* runs, you can avoid much of that initial modeling time cost by 1) using OSMnx's HTTP response caching to avoid redoing the API query/download and 2) pickling your graph to disk if you don't want to manually rebuild it.
