### ISSUE TITLE
Include option to specify the level of detail of the downloaded network

### ISSUE THREAD

**Issue by harisbal** [gboeing/osmnx#72]
First of all thanks a lot @gboeing for this amazing library

Really often I need to download the main network of an area. I was thinking to include another type in the _network_type_ e.g. _network_type_='drive_main'

Another idea would be to make it even more generic and specify the lower level of detail required in the network e.g. _network_type_='drive_main_primary' for higways taged _primary_ and above

I could try to implement the second option if you agree with the idea

Cheers

**Comment by gboeing** [comment]
This might be a useful feature. For what it's worth, OSMnx can effectively do this now after having downloading all drivable street types. For instance:

```python
import osmnx as ox
ox.config(use_cache=True, log_console=True)
G = ox.graph_from_bbox(33.397, 33.361, -111.855, -111.914, network_type='drive', simplify=False)
fig, ax = ox.plot_graph(ox.project_graph(G))
```

So that's our full drivable street network. Now we remove all edges that are not secondary or higher:

```python
hwy_types = ['motorway', 'motorway_link', 'primary', 'secondary']
gdf = ox.graph_to_gdfs(G, nodes=False)
mask = ~gdf['highway'].map(lambda x: isinstance(x, str) and x in hwy_types)
edges = zip(gdf[mask]['u'], gdf[mask]['v'], gdf[mask]['key'])
G.remove_edges_from(edges)
G = ox.remove_isolated_nodes(G)
G = ox.simplify_graph(G)
fig, ax = ox.plot_graph(ox.project_graph(G))
```

And that's the network of streets with level secondary or higher. Obviously the drawback is we've downloaded excess data that we don't intend to use, which consumes bandwidth and slows down graph construction somewhat.

How does that work for your use case? Is it effective enough or is there still substantial added value in considering adding a new feature?

**Comment by harisbal** [comment]
You are absolutely right, it doesn't seem like there is much added value including this feature.
Your solution works perfectly, thank you very much

**Comment by qchasserieau** [comment]
Hello,
Thank you for OSMNX that I use in a weekly basis.
Although small roads can be filtered out after the download. When working with a bad connection or in a large area, it would be handy to be able to download (and process) only the main street. Say : with an highway type in a given list of possibilities.

**Comment by gboeing** [comment]
@qchasserieau yes this functionality exists.

**Comment by qchasserieau** [comment]
Thank you,
For those who are interested, you can pass a custom filter instead of the network type to ox.graph_from_polygon.
I got an example of such filter with the following `print(ox.get_osm_filter('drive'))`
Then I customized it : 
`custom_filter = '["area"!~"yes"]["highway"!~"residential|cycleway|footway|path|pedestrian|steps|track|corridor|elevator|escalator|proposed|construction|bridleway|abandoned|platform|raceway|service"]["motor_vehicle"!~"no"]["motorcar"!~"no"]["access"!~"private"]["service"!~"parking|parking_aisle|driveway|private|emergency_access"]'`
then `custom = ox.graph_from_polygon(hull, custom_filter=custom_filter)`
It seems to be about twice faster to download the network when filtering out residential roads in paris.
![osmnx](https://user-images.githubusercontent.com/32388980/75903455-e40a8000-5e41-11ea-997b-a70e192f0269.PNG)
