### ISSUE TITLE
K shortest paths

### ISSUE THREAD

**Issue by harisbal** [gboeing/osmnx#76]
Calculating the k-shortest paths between an OD pair is quite common task. Unfortunately, the netwotkX function [shortest_simple_paths](http://networkx.readthedocs.io/en/stable/reference/generated/networkx.algorithms.simple_paths.shortest_simple_paths.html) cannot be executed on a multigraph as returned by nx.
A [manual conversion](https://stackoverflow.com/questions/15590812/networkx-convert-multigraph-into-simple-graph-with-weighted-edges#) to simple graph is possible but I was wondering if a better approach could be introduced.

**Comment by gboeing** [comment]
@harisbal yes *k*-shortest paths is a very useful calculation for street network analysis. As you mention, we can perform a manual conversion from MultiDiGraph to DiGraph, like the example on StackOverflow. What do you have in mind as a better approach?

**Comment by harisbal** [comment]
Initially, I was thinking to implement in ox something similar to the StackOverflow approach but I understand that this may cause some confusion since the weights can be aggregated in multiple ways.
Maybe I should check why the operation is not implemented in nx and try to deal with the problem at it's source. Sorry to bother, I just wanted to suggest it as a future enhancement, although that doesn't seem so straightforward.

**Comment by gboeing** [comment]
@harisbal thanks for clarifying. Agreed, trying to address this at the source (networkx) -- or at least understanding why it's not implemented there -- sounds like the best bet. Due to the potential complexity of having to plan for multiple ways in which users may want to aggregate edge weights, I'd rather see this either added to networkx or created ad hoc by users who want a DiGraph. A gist that demonstrates how to do this and includes a couple comments about weight aggregating might be helpful.

**Comment by harisbal** [comment]
Thanks for the comments @gboeing . 
I'll keep you posted if there is any update. 
Cheers
