### ISSUE TITLE
Can't pull shapefile for San Jose

### ISSUE THREAD

**Issue by DuongVu39** [gboeing/osmnx#777]
**Problem description**
I was trying to pull shapefile for city of San Jose and no matter what I did, it seems like it couldn't find it in the database. This only happened with city of San Jose, California, US so far.

**Environment information**
  - MacOS
  - Python version: 3.8
  -OSMnx version: 1.1.1

**A complete minimal reproducible example**

First I tried to query using the name:
```python
sj = ox.geocode_to_gdf("San Jose, California, USA", by_osmid=True)
```

This gave me this error:
<details>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/f_/08wxj0sd66lg1bd31x__k3lr0000gn/T/ipykernel_3635/1179218762.py in <module>
----> 1 sj = ox.geocode_to_gdf("San Jose, California, USA", by_osmid=True)
      2 sj

~/.pyenv/versions/3.8.3/envs/project_name/lib/python3.8/site-packages/osmnx/geocoder.py in geocode_to_gdf(query, which_result, by_osmid, buffer_dist)
    108     gdf = gpd.GeoDataFrame()
    109     for q, wr in zip(query, which_result):
--> 110         gdf = gdf.append(_geocode_query_to_gdf(q, wr, by_osmid))
    111 
    112     # reset GeoDataFrame index and set its CRS

~/.pyenv/versions/3.8.3/envs/project_name/lib/python3.8/site-packages/osmnx/geocoder.py in _geocode_query_to_gdf(query, which_result, by_osmid)
    156     if not results:
    157         # if no results were returned, raise error
--> 158         raise ValueError(f'Nominatim geocoder returned 0 results for query "{query}"')
    159 
    160     elif by_osmid:

ValueError: Nominatim geocoder returned 0 results for query "San Jose, California, USA"
</details>

Then I tried to look at openstreetmap website to find San Jose ID: https://www.openstreetmap.org/relation/112143#map=11/37.3108/-121.8967
This gives me ID: 112143
So I tried both 112143 and R 112143 id in the code below:

```python
sj = ox.geocode_to_gdf("R112143", by_osmid=True)
```

This gave me this error:
<details>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/f_/08wxj0sd66lg1bd31x__k3lr0000gn/T/ipykernel_3635/1179218762.py in <module>
----> 1 sj = ox.geocode_to_gdf("San Jose, California, USA", by_osmid=True)
      2 sj

~/.pyenv/versions/3.8.3/envs/project_name/lib/python3.8/site-packages/osmnx/geocoder.py in geocode_to_gdf(query, which_result, by_osmid, buffer_dist)
    108     gdf = gpd.GeoDataFrame()
    109     for q, wr in zip(query, which_result):
--> 110         gdf = gdf.append(_geocode_query_to_gdf(q, wr, by_osmid))
    111 
    112     # reset GeoDataFrame index and set its CRS

~/.pyenv/versions/3.8.3/envs/project_name/lib/python3.8/site-packages/osmnx/geocoder.py in _geocode_query_to_gdf(query, which_result, by_osmid)
    156     if not results:
    157         # if no results were returned, raise error
--> 158         raise ValueError(f'Nominatim geocoder returned 0 results for query "{query}"')
    159 
    160     elif by_osmid:

ValueError: Nominatim geocoder returned 0 results for query "San Jose, California, USA"
</details>

**Comment by gboeing** [comment]
In your first example, you intended to query by place name, but you parameterized the function to query by OSM ID instead of place name. So that error you see is to be expected. See [the docs](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.geocoder.geocode_to_gdf) for usage details.

In your second example, you found the relation ID on openstreetmap.org, but all that matters is whether it can be found by the Nominatim API. As the function docs state, this function will: "Retrieve place(s) by name or ID from the Nominatim API as a GeoDataFrame." So the entity you seek must be retrievable from the Nominatim API. But as you can see [on Nominatim](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=112143), no such relation can be found. So OSMnx is behaving as expected: that entity cannot be found via the Nominatim API.

The question of *why* it cannot be found via the Nominatim API is a good one, but must be asked of the Nominatim developers as I cannot help you there!

**Comment by mtmail** [comment]
Linking the resolved https://github.com/osm-search/Nominatim/issues/2521 in case anybody encounters similar error message.

**Comment by gboeing** [comment]
Interesting. Thanks for following up!
