### ISSUE TITLE
Add lengths to a select number of edges via osmnx.distance.add_edge_lengths

### ISSUE THREAD

**Issue by pmlpm1986** [gboeing/osmnx#830]
**Is your feature proposal related to a problem?**

No, I am proposing an enhancement that should make osmnx more flexible and useful.

If I add edges to a networkx object after I use osmnx, these won't have length attributes unless I add them. If the method add_edge_lengths allowed me to specify the target edges, this process can be made faster.

**Describe the solution you'd like to propose**

I thnk osmnx.distance.add_edge_lengths could be have an additional parameter to allow the user to specify which edges need to have that length attribute computed and added. 

The default value (uvk = None) would be to add the length attributes to all edges, since that is how it is currently used.

A simple if could switch between all edges or a select few:

if uvk == None:
    uvk = tuple(G.edges)

**Describe alternatives you've considered**

I also considered using edge filters but these don't provide as much flexibility.

**Comment by gboeing** [comment]
This seems like a good idea. Would you like to open a PR to contribute it?

**Comment by pmlpm1986** [comment]
Yes. I have begun to test my code and it partially performs as expected:
a) if I apply the method to a few edges, those edges get the same lengths as if I computed them manually, which is how it should be;
b) if I compute all the edge lengths from scratch (uvk=None) those that already had lengths get lengths that differ from the original values. I don't really understand why this happens. Do we get different floating point errors with vectorial functions?

**Comment by gboeing** [comment]
> those that already had lengths get lengths that differ from the original values. I don't really understand why this happens.

That is as expected. The function calculates edge lengths as straight-line distance from node `u` to node `v`. When OSMnx automatically runs it upon graph creation, it does it *before* [simplifying](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.simplification.simplify_graph) the graph. This means that it calculates the straight-line lengths of edge segments that they themselves are all straight. Only after simplification do edges take on a (potentially) curvilinear geometry. When you recalculate edge lengths later, you're calculating straight-line distances which necessarily ignore the curvilinear geometry. You only want to calculate edge lengths on a graph with all straight edges (such as an unsimplified graph), which is why the function's docstring says:

> Ensure graph is in unprojected coordinates, and unsimplified to get accurate distances

**Comment by gboeing** [comment]
Resolved by #831
