### ISSUE TITLE
Source and sink are the same node

### ISSUE THREAD

**Issue by marciorpcoelho** [gboeing/osmnx#88]
> Problem description:

I tried to retrieve the extended stats from a squared cell, but for some of cells it works flawlessly, while for others it returns the error: _networkx.exception.NetworkXError: source and sink are the same node_.
The only difference between cells are the coordinates used.

> What operating system, architecture, Python version, and OSMnx version are you using?
Mint Linux, Pycharm Community Edition 2016.3.3, OSMnx version 0.5.3t

> Complete list of your environment's packages and their versions:

<details>
asn1crypto (0.22.0)
branca (0.2.0)
cffi (1.10.0)
click (6.7)
click-plugins (1.0.3)
cligj (0.4.0)
conda (4.3.22)
cryptography (1.8.1)
cycler (0.10.0)
decorator (4.1.2)
descartes (1.1.0)
Fiona (1.7.8)
folium (0.3.0)
geopy (1.11.0)
idna (2.5)
Jinja2 (2.9.5)
MarkupSafe (1.0)
matplotlib (2.0.2)
munch (2.2.0)
networkx (1.11)
numpy (1.13.1)
osmnx (0.5.3)
packaging (16.8)
pandas (0.20.3)
pip (9.0.1)
psycopg2 (2.7.1)
pycosat (0.6.2)
pycparser (2.17)
pyOpenSSL (17.0.0)
pyparsing (2.1.4)
pyproj (1.9.5.1)
PySAL (1.13.0)
python-dateutil (2.6.1)
pytz (2017.2)
requests (2.14.2)
Rtree (0.8.3)
scipy (0.19.1)
setuptools (27.2.0)
Shapely (1.5.17.post1)
six (1.10.0)
SQLAlchemy (1.1.11)
tornado (4.5.1)
vincent (0.4.4)
wheel (0.29.0)
</details>

> Code that reproduces the issue

This works without a problem:
```python
G = ox.graph_from_bbox(41.149962,  41.147714, -8.583804, -8.586790, network_type='drive')
extended_stats = ox.extended_stats(G, connectivity=True, ecc=True, anc=True, bc=True)
print extended_stats
```

While this does not:
```python
G = ox.graph_from_bbox(41.149962, 41.147714, -8.610677, -8.613662, network_type='drive')
extended_stats = ox.extended_stats(G, connectivity=True, ecc=True, anc=True, bc=True)
print extended_stats
```

Sorry if it's something basic or obvious, i'm still learning the rope with python and OSMnx.
Thanks in advance.

**Comment by gboeing** [comment]
Hmmm it looks like the error is occurring in NetworkX's implementation of the Edmonds–Karp algorithm, which is called by NetworkX's `edge_connectivity()` function. Is it necessary to calculate node and edge connectivity for your graph? For what it's worth, it appears that both values are merely 1, as is typical of a spatial graph. If not, you can just run:

```python
extended_stats = ox.extended_stats(G, connectivity=False, ecc=True, anc=True, bc=True)
```

And it'll all work.

**Comment by marciorpcoelho** [comment]
Thanks for the reply, by turning Connectivity off i was able to calculate other metrics, but oddly enough, Diameter and Radius all returned zero. I thought those two metrics only depended on Eccentricity parameter?

**Comment by gboeing** [comment]
@marciorpcoelho the issue is that you have a tiny graph. It has like 11 edges and seems to be one-way streets. NetworkX needs a strongly-connected graph to calculate eccentricity, but the largest strongly-connected component in this small graph only contains 1 node. Hence your numbers. Just use a larger network to perform a meaningful topology analysis.

```python
G = ox.graph_from_address('Porto, Portugal', distance=1000, network_type='drive')
ox.extended_stats(G, ecc=True)
```

Note that most topological analyses have very high time complexity and will take a very long time to run on large graphs.

**Comment by marciorpcoelho** [comment]
Ah, now i undertstand it, thanks! I'm doing a graph analysis of a city dicretized in square cells, so i can't use a larger network, but your comment has helped to understand what is happening and in that way explain in project.
Thanks for your time!

**Comment by gboeing** [comment]
I see. Bear in the mind that any spatial definition of a city street network imposes an artificial boundary on the network. This is most apparent when using small boundaries, such as discretized square cells. While these artificial boundaries may not drastically impact metric measures (such as intersection density or block length -- other than creating larger errors due to small samples), they can significantly impact topological measures as you see in this example. If the cells are too small, you may not get meaningful measurements at that scale.

**Comment by marciorpcoelho** [comment]
Thanks for heads-up, i'll keep that in mind!
