### ISSUE TITLE
Managing Indexes when Converting to GeoDataFrame

### ISSUE THREAD

**Issue by Yozpoz64** [gboeing/osmnx#881]
A lot of osmnx functions require the conversion of the nx graph to a geodataframe. In the conversion of nodes, the OSMID is set to Index/MultiIndex. Thus an OSMID (or other int-like scalar) is required in node data to use osmnx. This is problematic when using other libraries to obtain a graph, such as nx or momepy. These may result in graphs that do not include OSMID - for example, momepy can produce graphs from geodataframes that have a tuple of (x, y) as the node identifier. 

I suggest adding more parameters in the `graph_to_gdfs` function to modify indexes. Possibly a boolean that determines whether an index is passed through, and if so to use a default index or what is passed through. I initially overcame this issue by commenting out some of the `graph_to_gdfs` to not mess with the default index.

If this feature were added, graphs obtained from other libraries could (more easily) take advantage of osmnx's functions.

**Comment by gboeing** [comment]
Hi @Yozpoz64 thanks for using OSMnx and suggesting this enhancement. I'm possibly open to it, with a couple of caveats. The most important is maintaining consistent indexes throughout the package's data structures (e.g., NetworkX MultiDiGraphs and GeoPandas GeoDataFrames). Whether the specific object is a MultiDiGraph or a GeoDataFrame, its constituent elements (nodes, edges) must have consistent indexing that remains intact regardless of which data structure they're currently in. As OSMnx's primary use case is OSM data, that index is OSMID by default for nodes.

> I initially overcame this issue by commenting out some of the graph_to_gdfs to not mess with the default index.

In general, it won't be as simple as this, because many of OSMnx's other features expect specific data and index structures and could break. 

> I suggest adding more parameters in the graph_to_gdfs function to modify indexes. Possibly a boolean that determines whether an index is passed through, and if so to use a default index or what is passed through. 

Why not just reindex your GeoDataFrame to whatever you like, after OSMnx converted it from MultiDiGraph?

**Comment by gboeing** [comment]
Closed for inactivity. Can reopen if needed for further action.
