### ISSUE TITLE
AttributeError: module 'numpy' has no attribute '_no_nep50_warning'

### ISSUE THREAD

**Issue by vr00n** [gboeing/osmnx#920]
Hello Geoff,

On Google Colab, I used to be able to install osmnx with these 2 lines of code but now this does not seem to be working. I get the error  `AttributeError: module 'numpy' has no attribute '_no_nep50_warning'`

```
!pip install osmnx 
import osmnx as ox
```

I've tried to install (on Google Colab) via conda but that does not work as well.

Thanks!

**Comment by gboeing** [comment]
See #918. Can't really troubleshoot beyond that without all the details requested by the new issue template.

**Comment by vr00n** [comment]
Thanks Geoff. I'll check it out

**Comment by kuanb** [comment]
@vr00n I ran into your issue and thus was able to re-create your error. The issue was that you were using "too old" a version of `numpy`.

For me, I was using `numpy` version: `1.20.3`

Looking at [the latest tagged release](https://github.com/gboeing/osmnx/blob/255c948c454954b29a6a69cd4a16797bc908b754/requirements.txt), I see that `numpy` is req'd to be `numpy>=1.23`. Attempting to run w/ version 1.20.x triggers a KeyError related to that attribute `_no_nep50_warning`, which does not exist in older version of `numpy`.

**Comment by gboeing** [comment]
See also this description of the problem and a couple options to solve it: https://github.com/gboeing/osmnx/issues/918#issuecomment-1397471071
